name: Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  s3-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Checkout
      - uses: actions/checkout@master@v4

      - name: Upload to S3
      - uses: shallwefootball/s3-upload-action@master@v1
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: erkecanbazoglu.com
          source_dir: "."
