name: Upload to S3
on:
  pull_request:
    branches:
      - main
jobs:
  upload:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checking out to the repository
        uses: actions/checkout@v4

      - name: Setting up Node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installing dependencies
        run: npm ci

      - name: Building the project
        run: npm run build

      - name: Uploading to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: erkecanbazoglu.com
          source_dir: "dist"
